# Change these first
owner: tritagonist-io # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Demo Visitors
    url: https://demo.tricket.io/
  - name: Cinecenter Visitors
    url: https://kassa.cinecenter.nl/
  - name: Admin
    url: https://admin.tricket.io
  - name: Boxoffice
    url: https://box.tricket.io
assignees:
  - mikechernev
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tricket Uptime
  introTitle: "Tricket status information"
  introMessage: This is the status information about Tricket
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
